version: appveyor-{build}
image: Visual Studio 2019
shallow_clone: true
environment:
  CRASHEDIT_S3DEPLOY_ACCESSKEY_ID:
    secure: vm68Yr9iFdgnH98tSRvqx1Kg6pX49e2cm9685GwH554=
  CRASHEDIT_S3DEPLOY_ACCESSKEY_SECRET:
    secure: i2KP8L+z+Txf6sYqGwZ8d7I+kDxQfLRBfLimncCKu8xPv3oF6hFsvVKFRVh/Tnd+
configuration: Debug
platform: Any CPU
assembly_info:
  patch: true
  file: Version.cs
  assembly_version: '0.2.{build}'
  assembly_file_version: '0.2.{build}'
build_script:
  - msbuild CrashEdit.sln
after_build:
  - mkdir pkg
  - copy .\README.md pkg
  - copy .\CrashEdit\bin\Debug\Crash.dll pkg
  - copy .\CrashEdit\bin\Debug\Crash.UI.dll pkg
  - copy .\CrashEdit\bin\Debug\CrashEdit.exe pkg
  - copy .\CrashEdit\bin\Debug\CrashEdit.exe.config pkg
  - copy .\CrashEdit\bin\Debug\ISO2PSX.dll pkg
  - copy .\CrashEdit\bin\Debug\ja\Crash.UI.resources.dll pkg
  - copy .\CrashEdit\bin\Debug\ja\CrashEdit.resources.dll pkg
  - copy .\CrashHacks\bin\Debug\CrashHacks.exe pkg
  - copy .\OpenTK.dll pkg
  - copy .\OpenTK.GLControl.dll pkg
  - copy .\OpenTK-License.txt pkg
  - copy .\DiscUtils.dll pkg
  - copy .\DiscUtils-License.txt pkg
  - 7z a CrashEdit.zip .\pkg\*
  - move CrashEdit.zip CrashEdit-%APPVEYOR_BUILD_NUMBER%-%APPVEYOR_REPO_COMMIT%.zip
test: off
artifacts:
  - path: CrashEdit-$(APPVEYOR_BUILD_NUMBER)-$(APPVEYOR_REPO_COMMIT).zip
    name: CRASHEDIT-FULLZIP
deploy:
  - provider: S3
    access_key_id: $(CRASHEDIT_S3DEPLOY_ACCESSKEY_ID)
    secret_access_key: $(CRASHEDIT_S3DEPLOY_ACCESSKEY_SECRET)
    bucket: builds.crashedit.cbhacks.com
    region: us-east-1
    folder: appveyor/build-$(APPVEYOR_BUILD_NUMBER)
    max_error_retry: 2
    artifact: CRASHEDIT-FULLZIP
    on:
      branch: deprecate
